name: Test

on: 
  push:
    branches: 
    - main
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello
      run: echo 'Hello World'
  util-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout and clone
      uses: actions/checkout@v4.1.1
    - name: Install dependencies
      run: npm ci
    - name: Run util tests
      run: npm test utils
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout and clone
      uses: actions/checkout@v4.1.1
    - name: Install dependencies
      run: npm ci
    - name: Run integration tests
      run: npm test app